// <auto-generated />
using System;
using AraujosPokedex.Database.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AraujosPokedex.Database.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AraujosPokedex.Domain.Models.Pokemon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DateCaught")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsOwned")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Nickname")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("PrimaryType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("SecondaryType")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Pokemons", "dbo");
                });

            modelBuilder.Entity("AraujosPokedex.Domain.Models.Type", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.ToTable("Types", "dbo");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Normal"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Fire"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Water"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Grass"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Electric"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Psychic"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Ice"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Dragon"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Dark"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Fairy"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Fighting"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Flying"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Poison"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Ground"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Rock"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Bug"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Ghost"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Steel"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
